### ISSUE TITLE
Inquiry About Open Source Release

### ISSUE THREAD

**Issue by gcccccccccccc12345** [lukasHoel/3DGS-LM#1]
I wanted to express my appreciation for your excellent work on 3DGS-LM! Your insights into the training challenges of 3D Gaussian models are particularly impressive and highly relevant.
I’m curious if you have a specific timeline for when the code will be made available as open source.
Thank you, and I look forward to your response!

**Comment by 18128381510** [comment]
+1

**Comment by lukasHoel** [comment]
Hi, thanks for your interest. We are currently planning for a release until the end of the year.
