### ISSUE TITLE
Question about the training pipeline

### ISSUE THREAD

**Issue by DapengFeng** [lukasHoel/3DGS-LM#2]
Hi, @lukasHoel. I have a question about the 3DGS-LM training pipeline. Why do we need to train the first stage with the original 3DGS? Can we only optimize the Gaussian primitives with LM from scratch?

**Comment by lukasHoel** [comment]
Hi, yes it is possible to only optimize the Gaussians with LM from scratch. We show this in Fig. 4 in the paper and also in the released video. The main reason why we separate our method into two stages is the densification. The original 3DGS densifies Gaussians up to 140 times, which is not easily transferable to the granularity of only 5 LM iterations. Therefore we switch the optimizer after densification is completed.
